name: Merge Staging to Main
on:
  push:
    branches:
      - staging
jobs:
  merge:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge staging to main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main
          git merge --no-ff staging
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
